spring:
  autoconfigure:
    # Disable the UserDetailsServiceAutoConfiguration to prevent Spring Boot from auto-configuring a default UserDetailsService
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/member-management
    username: user
    password: password

  jpa:
    open-in-view: off
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
