name: Custom Discord Notifications

on:
  pull_request: # pr - opened, synchronize, reopened, closed 이벤트 발생 시 discord 알림
    types: [ opened, closed ]
  issues: # issues - opened, closed 이벤트 발생 시 discord 알림
    types: [ opened, closed ]
  push: # push - main, develop 브랜치에 push 이벤트 발생 시 discord 알림
    branches:
      - main
      - develop

jobs:
  handle_pr_events:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: PR Info
        run: |
          echo "repository_name=${{ github.repository }}" >> $GITHUB_ENV
          echo "pull_request_title=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "pull_request_url=${{ github.event.pull_request.html_url }}" >> $GITHUB_ENV
          echo "pull_request_author=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV
          echo "pull_request_changed_files=${{ github.event.pull_request.changed_files }}" >> $GITHUB_ENV

      - name: PR opened
        env:
          DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1403287687846428744/xmFCEt4_scWBvcvWgmTY6HmxBp8Sh_jEp6twaOck2vPeRMEqEPXgMQWM3vVYFwtn9PS_
        if: github.event.action == 'opened'
        run: |
          
          payload=$(jq -n \
            --arg title "${{ github.event.pull_request.title }}" \
            --arg url "${{ github.event.pull_request.html_url }}" \
            '{
              "embeds": [
                {
                  "title": "New PR Opened at \($repository_name)",
                  "description": "**PR Title-** \($title)\n[PR link](\$url)",
                  "color": 3447003
                }
                ]
            }')
          
            curl -H "Content-Type: application/json" \
                -X POST \
                -d "$payload" \
                "$DISCORD_WEBHOOK_URL"

      - name: PR closed
        env:
          DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1403287687846428744/xmFCEt4_scWBvcvWgmTY6HmxBp8Sh_jEp6twaOck2vPeRMEqEPXgMQWM3vVYFwtn9PS_
        if: github.event.action == 'closed'
        run: |
          if [[ "${{github.event.pull_request.changed_files}}" -eq 0 ]]; then
            change_msg="No files changed."
          else 
            change_msg="${{github.event.pull_request.changed_files}} files changed."}}
          fi
          
          payload=$(jq -n \
            --arg title "${{ github.event.pull_request.title }}" \
            --arg url "${{ github.event.pull_request.html_url }}" \
            --arg changes "$change_msg" \
            '{
              "embeds": [
                {
                  "title": "PR Closed at \($repository_name)",
                  "description": "**PR Title-** \($title)\n**Changes-** \($changes)\n[PR link](\$url)",
                  "color": 15158332
                }
                ]
            }')
          
            curl -H "Content-Type: application/json" \
                -X POST \
                -d "$payload" \
                "$DISCORD_WEBHOOK_URL"

      - name: PR merged
        env:
          DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1403287687846428744/xmFCEt4_scWBvcvWgmTY6HmxBp8Sh_jEp6twaOck2vPeRMEqEPXgMQWM3vVYFwtn9PS_
        if: github.event.action == 'opened'
        run: |
          if [[ "${{github.event.pull_request.changed_files}}" -eq 0 ]]; then
            change_msg="No files changed."
          else 
            change_msg="${{github.event.pull_request.changed_files}} files changed."}}
          fi
          
          payload=$(jq -n \
            --arg title "${{ github.event.pull_request.title }}" \
            --arg url "${{ github.event.pull_request.html_url }}" \
            --arg base_branch "${{ github.event.pull_request.base.ref }}" \
            --arg changes "$change_msg" \
            '{
              "embeds": [
                {
                  "title": "PR Merged at \($repository_name)",
                  "description": "**Base Branch-** \($base_branch)\n**PR Title-** \($title)\n**Changes-** \($changes)\n[PR link](\$url)",
                  "color": 3066993
                }
                ]
            }')
          
            curl -H "Content-Type: application/json" \
                -X POST \
                -d "$payload" \
                "$DISCORD_WEBHOOK_URL"

  handle_push_events:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Push Info
        run: |
          echo "repository_name=${{ github.repository }}" >> $GITHUB_ENV
          echo "pushed_branch=${{ github.ref }}" >> $GITHUB_ENV
          echo "pushed_commit=${{ github.head_commit.message }}" >> $GITHUB_ENV
          echo "pushed_commit_url=${{ github.head_commit.url }}" >> $GITHUB_ENV

      - name: Push Notification
        env:
          DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1403287687846428744/xmFCEt4_scWBvcvWgmTY6HmxBp8Sh_jEp6twaOck2vPeRMEqEPXgMQWM3vVYFwtn9PS_
        run: |
          payload=$(jq -n \
            --arg branch "${{ github.ref }}" \
            --arg commit "${{ github.head_commit.message }}" \
            --arg commit_url "${{ github.head_commit.url }}" \
            '{
              "embeds": [
                {
                  "title": "Commit Pushed at \($repository_name)",
                  "description": "**Branch-** \($branch)\n**Commit Message-** \($commit)\n[Commit link](\$commit_url)",
                  "color": 3066993452
                }
                ]
            }')
          
            curl -H "Content-Type: application/json" \
                -X POST \
                -d "$payload" \
                "$DISCORD_WEBHOOK_URL"